name: 🚀 Feature request
description: If you have a feature request 💡
title: '[Feature]: '
labels: ['enhancement']
body:
    - type: markdown
      attributes:
          value: |
              **Thanks :heart: for taking the time to fill out this feature request!** We kindly ask that you search to see if an issue [already exists](https://github.com/gremo/symfony-sail/issues?q=is%3Aissue+label%3Aenhancement+sort%3Acreated-desc+) for the feature.

    - type: dropdown
      attributes:
          label: To which environment is the feature request applicable?
          description: Specify whether the feature request targets the development container (i.e. Visual Studio Code), the production one, or both.
          options:
              - Development
              - Production
              - Both
      validations:
          required: true

    - type: textarea
      attributes:
          label: Description
          description: |
              A clear and concise description of the feature you're interested in.
      validations:
          required: true

    - type: textarea
      attributes:
          label: Suggested solution
          description: |
              Describe the solution you'd like. A clear and concise description of what you want to happen.

    - type: checkboxes
      attributes:
          label: Are you willing to contribute it?
          options:
              - label: I can work on a pull request to implement this feature
