name: Release

on:
    push:
      branches:
        - main
      paths-ignore:
        - LICENSE
        - README.md

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: marvinpinto/action-automatic-releases@latest
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  automatic_release_tag: latest
                  prerelease: true
                  title: "Development Build"
                  files: |
                      LICENSE
                      Dockerfile
