name: Update TOC

on:
    push:
        paths:
            - 'README.md'
            - '.github/workflows/update_toc.yaml'

jobs:
    generate:
        name: Generate
        runs-on: ubuntu-latest
        steps:
            - uses: technote-space/toc-generator@v4
              with:
                  TOC_TITLE: 👇 Table of <b>contents</b>
                  COMMIT_MESSAGE: 'chore(docs): Update TOC'
                  MAX_HEADER_LEVEL: 2
                  FOLDING: true
